dataset:
  name: coco_aug
  root: ./datasets/coco/
  img_folder: val2014
  emb_folder: precomputed/groupvit
  img_emb_filename: coco-img-embeddings.pkl
  capt_emb_filename: coco-capt-embeddings.pkl
  annotation_file: annotations/dataset_coco.json
  augmentations: annotations/dataset_coco_aug.json

model:
  name: nvidia/groupvit-gcc-yfcc
  path:  TBA
  max_seq_length: 325

dcg:
  relevance_estimator:
    name: clip-ViT-B-32
    sim_score: cosine

results:
  dir: ./results
  folder: groupvit