dataset:
  root: /notebooks/evaluating-cmr-in-mm/datasets/coco/
  img_folder: val2014
  emb_folder: flava
  img_emb_filename: coco-img-embeddings.pkl
  capt_emb_filename: coco-capt-embeddings.pkl
  annotation_file: annotations/dataset_coco.json

model:
  name: facebook/flava-full
  path: TBA
  pooling: mean
  padding: max_length
  max_seq_length: 77

dcg:
  relevance_estimator:
    name: clip-ViT-B-32
    sim_score: cosine

results:
  dir: /notebooks/evaluating-cmr-in-mm/results
