dataset:
  name: f30k
  root: /Users/mhendriksen/Desktop/repositories/datasets/f30k/
  img_folder: flickr30k-images
  emb_folder: precomputed/bridgetower
  img_emb_filename: f30k-img-embeddings.pkl
  capt_emb_filename: f30k-capt-embeddings.pkl
  annotation_file: annotations/dataset_flickr30k.json

model:
  name: BridgeTower/bridgetower-large-itm-mlm-itc
  path: TBA
  max_seq_length: 330
  
dcg:
  relevance_estimator:
    name: clip-ViT-B-32
    sim_score: cosine

results:
  dir: /Users/mhendriksen/Desktop/repositories/evaluating-cmr-in-mm/results
  folder: bridgetower
