dataset:
  name: f30k
  root: /notebooks/evaluating-cmr-in-mm/datasets/f30k/
  img_folder: flickr30k-images
  emb_folder: flava
  img_emb_filename: f30k-img-embeddings.pkl
  capt_emb_filename: f30k-capt-embeddings.pkl
  annotation_file: annotations/dataset_flickr30k.json

model:
  name: facebook/flava-full
  path: TBA
  pooling: mean
  padding: max_length
  max_seq_length: 77

dcg:
  relevance_estimator:
    name: clip-ViT-B-32
    sim_score: cosine

results:
  dir: /notebooks/evaluating-cmr-in-mm/results
  folder: flava
